tests/unit/test_openapi_spec.py
In the workflow to automatically generate documentation whenever a change is made to relevant files, the push is failing since this repo has no tests, and it thinks that there is something wrong with the testing setup. Adding this dummy test will hopefully resolve the issue and let the workflow push to this repo.
=> Added a dummy test to prevent workflow from quitting

invoices.openapi.json, pii.openapi.json
Adding specs for PII and Invoice models to separate out "specialized" forms models
=> Lp 4286 2025 02 27

vkg.openapi.json
This is the correct PR made from 2025-02-27 branch (rather than main)
=> 02-27: Various updates to VKG script from QA

vkg.openapi.json
This is the correct PR made from 2025-02-13 branch (rather than main)
=> 02-13: Various updates to VKG script from QA

vkg.openapi.json
This is the correct PR made from 2025-02-06 branch (rather than main)
=> 02-06: Various updates to VKG script from QA

extract.openapi.json, rikai2.openapi.json, riky2.openapi.json
The AutoGenerated PR but the Examples are fine
=> 2025-03-27-Declan: Fixed Examples

extract.openapi.json, rikai2.openapi.json, riky2.openapi.json
A change was made to a custom-rikai endpoint, so a change to the documentation is necessary. Created by a Github Action.
=> Updated documentation for custom-rikai endpoints

rikai2.openapi.json
New request and response parameters per discussion with Caroline and Lester.
=> Add new request response parameters

extract.openapi.json, rikai2.openapi.json, riky2.openapi.json
- Set default version of OCR to reflect API behavior
- Warn users that version 2 is required as input to ocr methods
=> LP-4484: Default OCR version discrepancy

forms.openapi.json
Ticket: https://lazarus-ai.atlassian.net/browse/LP-4596
=> LP-4596: Updating Forms Spec for Status Id

forms.openapi.json
https://lazarus-ai.atlassian.net/browse/LP-4596
=> LP-4596: Document ID => Status ID Forms Async

extract.openapi.json, rikai2.openapi.json, riky2.openapi.json
Webhook is actually required now
=> Modified endpoint descriptions for async endpoints

.gitignore, ocr.openapi.json
https://lazarus-ai.atlassian.net/browse/LP-4607
**summary**
- add .gitignore
- remove `statusId`
- update error code and example message
- remove version in body
- add `heic` image support
- default version to `2025-05-22`
- added `sftp` body param
=> LP-4607 update ocr docs

rikai2.openapi.json, riky2.openapi.json
https://lazarus-ai.atlassian.net/browse/LP-5383
**summary**
- add `model` field to rikai2 and riky2 error response (except `207`)
=> LP-5383 add model to error response

developer.openapi.json
This file is needed for the documentation to show up on https://docs.lazarusforms.com/developer/
=> 2025-07-24: Add developer api info

pii.openapi.json
=> 2025-07-24: pii was incorrectly set - setting to match 7/10

extract.openapi.json, rikai2.openapi.json, riky2.openapi.json
=> LP-4841 add new fields to GET response

extract.openapi.json, rikai2.openapi.json, riky2.openapi.json
A change was made to a custom-rikai endpoint, so a change to the documentation is necessary. Created by a Github Action.
=> 2025-08-07 Updated `code` field descriptions

extract.openapi.json, rikai2.openapi.json, riky2.openapi.json
address error with webhook error url
=> 9/4/25: Webhook Errors URL Update

pii.openapi.json
Needed for docs changes that will be coming. Current PII is saas
=> VPC Docs - fix staging specs for PII
